In [1]:
import numpy as np

In [5]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [6]:
sample_matrix[1,2]

21

In [7]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [8]:
sample_matrix[2]

array([56, 76, 24,  7])

In [9]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [10]:
sample_matrix[1,(1,2)]

array([23, 21])

selection techniques

In [11]:
sample_array=np.arange(1,20)

In [12]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [13]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [14]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [15]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [16]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [17]:
np.max(sample_array)

19

In [18]:
np.min(sample_array)

1

In [19]:
np.argmax(sample_array)

18

In [20]:
np.argmin(sample_array)

0

In [21]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [22]:
np.std(sample_array)

5.477225575051661

In [23]:
np.var(sample_array)

30.0

In [24]:
np.mean(sample_array)

10.0

In [31]:
array=np.random.randn(3,4)
array

array([[-0.87110092,  1.15517479, -0.27395295,  1.62360662],
       [ 0.18772072,  0.17311966,  0.04372382,  0.43918196],
       [-0.1313439 , -0.63563588, -0.6386721 ,  2.05091662]])

In [27]:
np.round(array,decimals=2)

array([[ 0.07, -2.28,  0.2 , -1.52],
       [ 0.54,  2.44, -1.31,  0.37],
       [-1.24,  0.17, -0.5 ,  1.74]])

In [29]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

###Pandas

In [52]:
import pandas as pd
import numpy as np

###Pandas dataframe and indexing

In [32]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [33]:
sports1['football']

2

In [34]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [35]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [37]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.714679  0.243092  0.057376  0.962975  0.148648
B  0.713186  0.349241  0.560448  0.793676  0.146423
C  0.805579  0.739549  0.558335  0.997188  0.670081
D  0.513148  0.980556  0.246821  0.038502  0.148325
E  0.035474  0.141694  0.830178  0.979618  0.609810
F  0.232540  0.858373  0.443847  0.983869  0.688711
G  0.579636  0.955461  0.110315  0.408651  0.703028
H  0.954705  0.594284  0.344529  0.271313  0.627902

In [38]:
df1["Score1"]

A    0.714679
B    0.713186
C    0.805579
D    0.513148
E    0.035474
F    0.232540
G    0.579636
H    0.954705
Name: Score1, dtype: float64

In [39]:
df1[["Score1","Score2"]]

Score1    Score2
A  0.714679  0.243092
B  0.713186  0.349241
C  0.805579  0.739549
D  0.513148  0.980556
E  0.035474  0.141694
F  0.232540  0.858373
G  0.579636  0.955461
H  0.954705  0.594284

In [41]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.714679  0.243092  0.057376  0.962975  0.148648  0.957771
B  0.713186  0.349241  0.560448  0.793676  0.146423  1.062427
C  0.805579  0.739549  0.558335  0.997188  0.670081  1.545128
D  0.513148  0.980556  0.246821  0.038502  0.148325  1.493703
E  0.035474  0.141694  0.830178  0.979618  0.609810  0.177168
F  0.232540  0.858373  0.443847  0.983869  0.688711  1.090913
G  0.579636  0.955461  0.110315  0.408651  0.703028  1.535097
H  0.954705  0.594284  0.344529  0.271313  0.627902  1.548989

In [56]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [55]:
df["ID"]

0    101
1    102
2    103
3    107
4    176
Name: ID, dtype: object

In [57]:
df[['ID','Name']]

ID   Name
0  101   John
1  102  Mercy
2  103  Akash
3  107  Kavin
4  176  Lally

In [58]:
df=df.drop('ID',axis=1)


In [59]:
df

Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
3  Kavin      87
4  Lally     123

In [60]:
df.drop(3)

Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
4  Lally     123